/** Центральный контент сайта — правьте тексты здесь под заказчика */

export const brand = {
  name: "ШИКАРДОРС.РФ",
  tagline: "Двери. Замер. Монтаж под ключ",
  city: "Тюмень",
  description: "Салон межкомнатных и входных дверей с установкой",
  email: "hello@shikardors.ru",
  whatsapp: "https://wa.me/79199000001",
  telegram: "https://t.me/shikardors",
  phoneMain: "+7 (3452) 91-92-00",
  phoneMainHref: "tel:+73452919200",
};

export const salons = [
  {
    id: "zarechnaya",
    name: "ТЦ Заречная · Блошинка",
    address: "ул. Ю.-Р.Г. Эрвье, 22",
    phone: "+7 (3452) 91-92-00",
    phoneHref: "tel:+73452919200",
    hours: "Ежедневно 09:00–20:00",
  },
  {
    id: "moskovsky",
    name: "Московский тракт",
    address: "Московский тракт, 120с2, оф. 255",
    phone: "+7 (958) 260-44-54",
    phoneHref: "tel:+79582604454",
    hours: "Ежедневно 09:00–18:30",
  },
  {
    id: "permyakova",
    name: "ТЦ Перестрой-ка",
    address: "ул. Пермякова, 1а",
    phone: "+7 (992) 305-60-61",
    phoneHref: "tel:+79923056061",
    hours: "Ежедневно 09:00–19:00",
  },
];

export const nav = [
  {
    label: "Межкомнатные",
    href: "/catalog/interior",
    columns: [
      {
        title: "По конструкции",
        links: [
          { label: "Распашные", href: "/catalog/interior?type=swing" },
          { label: "Раздвижные / купе", href: "/catalog/interior?type=sliding" },
          { label: "Складные", href: "/catalog/interior?type=folding" },
          { label: "Скрытые", href: "/catalog/interior?type=hidden" },
          { label: "Перегородки", href: "/catalog/interior?type=partition" },
        ],
      },
      {
        title: "По стилю",
        links: [
          { label: "Современные", href: "/catalog/interior?style=modern" },
          { label: "Неоклассика", href: "/catalog/interior?style=neoclassic" },
          { label: "Лофт", href: "/catalog/interior?style=loft" },
          { label: "Классика", href: "/catalog/interior?style=classic" },
        ],
      },
      {
        title: "По отделке",
        links: [
          { label: "Экошпон", href: "/catalog/interior?finish=eco" },
          { label: "Натуральный шпон", href: "/catalog/interior?finish=veneer" },
          { label: "Эмаль", href: "/catalog/interior?finish=enamel" },
          { label: "Под покраску", href: "/catalog/interior?finish=paint" },
        ],
      },
    ],
  },
  {
    label: "Входные",
    href: "/catalog/entrance",
    columns: [
      {
        title: "По назначению",
        links: [
          { label: "В квартиру", href: "/catalog/entrance?purpose=flat" },
          { label: "В дом / коттедж", href: "/catalog/entrance?purpose=house" },
          { label: "Для дачи", href: "/catalog/entrance?purpose=dacha" },
          { label: "Противопожарные", href: "/catalog/entrance?purpose=fire" },
        ],
      },
      {
        title: "По конструкции",
        links: [
          { label: "С терморазрывом", href: "/catalog/entrance?feature=thermo" },
          { label: "С зеркалом", href: "/catalog/entrance?feature=mirror" },
          { label: "С шумоизоляцией", href: "/catalog/entrance?feature=noise" },
          { label: "Двустворчатые", href: "/catalog/entrance?feature=double" },
        ],
      },
      {
        title: "По бюджету",
        links: [
          { label: "До 25 000 ₽", href: "/catalog/entrance?price=0-25000" },
          { label: "25–50 000 ₽", href: "/catalog/entrance?price=25000-50000" },
          { label: "от 50 000 ₽", href: "/catalog/entrance?price=50000+" },
        ],
      },
    ],
  },
  {
    label: "Полы",
    href: "/catalog/flooring",
    columns: [
      {
        title: "Тип",
        links: [
          { label: "Ламинат", href: "/catalog/flooring?type=laminate" },
          { label: "Инженерная доска", href: "/catalog/flooring?type=engineered" },
          { label: "SPC / кварцвинил", href: "/catalog/flooring?type=spc" },
          { label: "Паркетная доска", href: "/catalog/flooring?type=parquet" },
        ],
      },
      {
        title: "Оттенок",
        links: [
          { label: "Светлый", href: "/catalog/flooring?tone=light" },
          { label: "Натуральный", href: "/catalog/flooring?tone=natural" },
          { label: "Тёмный", href: "/catalog/flooring?tone=dark" },
        ],
      },
      {
        title: "Класс",
        links: [
          { label: "33 класс", href: "/catalog/flooring?grade=33" },
          { label: "34 класс", href: "/catalog/flooring?grade=34" },
          { label: "Влагостойкий", href: "/catalog/flooring?grade=wet" },
        ],
      },
    ],
  },
  {
    label: "Бамбук",
    href: "/catalog/bamboo",
    columns: [
      {
        title: "Формат",
        links: [
          { label: "Стеновые панели", href: "/catalog/bamboo?type=wall" },
          { label: "Рейки / ламели", href: "/catalog/bamboo?type=slat" },
          { label: "Декор-плитка", href: "/catalog/bamboo?type=tile" },
        ],
      },
      {
        title: "Цвет",
        links: [
          { label: "Натуральный", href: "/catalog/bamboo?tone=natural" },
          { label: "Карбон", href: "/catalog/bamboo?tone=carbon" },
          { label: "Выбеленный", href: "/catalog/bamboo?tone=bleached" },
        ],
      },
      {
        title: "Монтаж",
        links: [
          { label: "Клей", href: "/catalog/bamboo?mount=glue" },
          { label: "Система шип-паз", href: "/catalog/bamboo?mount=click" },
          { label: "На обрешётку", href: "/catalog/bamboo?mount=batten" },
        ],
      },
    ],
  },
  {
    label: "Фурнитура",
    href: "/catalog/hardware",
    columns: [
      {
        title: "Категории",
        links: [
          { label: "Ручки", href: "/catalog/hardware?cat=handles" },
          { label: "Замки", href: "/catalog/hardware?cat=locks" },
          { label: "Петли", href: "/catalog/hardware?cat=hinges" },
          { label: "Доводчики", href: "/catalog/hardware?cat=closers" },
        ],
      },
    ],
  },
  {
    label: "Услуги",
    href: "/services",
    columns: [
      {
        title: "Под ключ",
        links: [
          { label: "Бесплатный замер", href: "/measure" },
          { label: "Установка дверей", href: "/services#install" },
          { label: "Доставка и оплата", href: "/services#delivery" },
          { label: "Гарантия", href: "/services#warranty" },
        ],
      },
    ],
  },
  { label: "Акции", href: "/promotions" },
  { label: "О нас", href: "/about" },
  { label: "Контакты", href: "/contacts" },
];

export const categoryRow = [
  { label: "Межкомнатные", href: "/catalog/interior", icon: "interior" },
  { label: "Входные", href: "/catalog/entrance", icon: "entrance" },
  { label: "Полы", href: "/catalog/flooring", icon: "flooring" },
  { label: "Бамбук", href: "/catalog/bamboo", icon: "bamboo" },
  { label: "Фурнитура", href: "/catalog/hardware", icon: "hardware" },
  { label: "Замерщик", href: "/measure", icon: "measure" },
  { label: "Акции", href: "/promotions", icon: "promo" },
];

export const heroSlides = [
  {
    id: "hidden",
    title: "Дверь как часть архитектуры",
    text: "Скрытые системы и чистые линии — полный комплект от 25 000 ₽.",
    cta: "Смотреть скрытые",
    href: "/catalog/interior?type=hidden",
    image: "/media/hero-hidden.png",
  },
  {
    id: "finishes",
    title: "Оттенок, который совпадёт с интерьером",
    text: "Живые образцы в трёх салонах Тюмени — не угадывание по экрану.",
    cta: "Открыть каталог",
    href: "/catalog/interior",
    image: "/media/hero-finish.png",
  },
  {
    id: "entrance",
    title: "Входные двери с понятной сметой",
    text: "Терморазрыв, шум, безопасность — считаем комплект и монтаж до договора.",
    cta: "Входные двери",
    href: "/catalog/entrance",
    image: "/media/hero-entrance.png",
  },
  {
    id: "install",
    title: "Монтаж, после которого не стыдно принимать работу",
    text: "Свои бригады, облагораживание проёма, сроки в договоре.",
    cta: "Вызвать замерщика",
    href: "/measure",
    image: "/media/hero-install.png",
  },
  {
    id: "showroom",
    title: "Три салона — потрогать цвет до покупки",
    text: "Экошпон, эмаль, шпон и фурнитура вживую при нормальном свете.",
    cta: "Адреса салонов",
    href: "/contacts",
    image: "/media/hero-showroom.png",
  },
];

export const brands = [
  "Optima Porte",
  "ProfilDoors",
  "Владимирская фабрика",
  "Стальная линия",
  "Torex",
  "Браво",
  "Дверной континент",
  "LA STELLA",
];

export const finishes = [
  { name: "Белый ясень", hex: "#e8e4dc", image: "/media/finish-white.png" },
  { name: "Графит", hex: "#3a3f46", image: "/media/finish-graphite.png" },
  { name: "Дуб натуральный", hex: "#b08a5a", image: "/media/finish-oak.png" },
  { name: "Чёрный мат", hex: "#1a1c1f", image: "/media/finish-black.png" },
  { name: "Капучино", hex: "#a89078", image: "/media/finish-cappuccino.png" },
  { name: "Эмаль мята", hex: "#c5d5cb", image: "/media/finish-mint.png" },
];

export const galleryImages = [
  "/media/g-extra-1.png",
  "/media/fork-interior.png",
  "/media/promo-1.png",
  "/media/p-rome.png",
  "/media/hero-install.png",
  "/media/g-extra-2.png",
  "/media/p-grand.png",
  "/media/promo-2.png",
];

export const visualCategories = [
  { label: "Скрытые", href: "/catalog/interior?type=hidden", image: "/media/cat-hidden.png" },
  { label: "Купе", href: "/catalog/interior?type=sliding", image: "/media/cat-coupe.png" },
  { label: "Эмаль", href: "/catalog/interior?finish=enamel", image: "/media/cat-enamel.png" },
  { label: "Терморазрыв", href: "/catalog/entrance?feature=thermo", image: "/media/cat-thermo.png" },
  { label: "С зеркалом", href: "/catalog/entrance?feature=mirror", image: "/media/cat-mirror.png" },
  { label: "Перегородки", href: "/catalog/interior?type=partition", image: "/media/cat-partition.png" },
];

export const productImages: Record<string, string> = {
  "turin-507": "/media/p-turin.png",
  symphony: "/media/p-symphony.png",
  "hidden-line": "/media/p-hidden.png",
  rome: "/media/p-rome.png",
  loft: "/media/p-loft.png",
  coupe: "/media/p-coupe.png",
  "sibir-sb3": "/media/p-sibir.png",
  "grand-ash": "/media/p-grand.png",
  stroygost: "/media/p-stroy.png",
  "thermo-elite": "/media/p-thermo.png",
  handle: "/media/finish-graphite.png",
  lock: "/media/cat-mirror.png",
  "floor-nordic": "/media/finish-white.png",
  "floor-honey": "/media/finish-oak.png",
  "floor-walnut": "/media/finish-graphite.png",
  "floor-spc-stone": "/media/finish-mint.png",
  "floor-spc-oak": "/media/finish-cappuccino.png",
  "floor-engineered": "/media/g-extra-1.png",
  "bamboo-natural": "/media/finish-oak.png",
  "bamboo-carbon": "/media/finish-black.png",
  "bamboo-bleached": "/media/finish-white.png",
  "bamboo-slat": "/media/cat-partition.png",
  "bamboo-slat-dark": "/media/finish-graphite.png",
  "bamboo-tile": "/media/g-extra-2.png",
  "porto-eco": "/media/p-turin.png",
  "velvet-enamel": "/media/p-rome.png",
  "fold-smart": "/media/p-coupe.png",
  "classic-pg": "/media/p-symphony.png",
  "invisible-pro": "/media/p-hidden.png",
  "glass-slim": "/media/p-loft.png",
  "nord-flat": "/media/p-sibir.png",
  "mirror-line": "/media/cat-mirror.png",
  "cottage-termo": "/media/p-thermo.png",
  "budget-steel": "/media/p-stroy.png",
  "double-grand": "/media/p-grand.png",
  "floor-oak-white": "/media/finish-white.png",
  "floor-wenge": "/media/finish-black.png",
  "floor-spc-beige": "/media/finish-cappuccino.png",
  "floor-parquet-oak": "/media/finish-oak.png",
  "floor-spc-dark": "/media/finish-graphite.png",
  "floor-ash-wide": "/media/g-extra-1.png",
  "bamboo-wide": "/media/finish-oak.png",
  "bamboo-smoke": "/media/finish-cappuccino.png",
  "bamboo-slat-thin": "/media/cat-partition.png",
  "bamboo-slat-bleach": "/media/finish-white.png",
  "bamboo-tile-dark": "/media/finish-black.png",
  "bamboo-acoustic": "/media/g-extra-2.png",
};

export const productGalleries: Record<string, string[]> = {
  "turin-507": ["/media/p-turin.png", "/media/fork-interior.png", "/media/finish-oak.png"],
  symphony: ["/media/p-symphony.png", "/media/hero-finish.png", "/media/finish-cappuccino.png"],
  "hidden-line": ["/media/p-hidden.png", "/media/cat-hidden.png", "/media/hero-hidden.png"],
  rome: ["/media/p-rome.png", "/media/cat-enamel.png", "/media/finish-white.png"],
  loft: ["/media/p-loft.png", "/media/cat-partition.png", "/media/cat-coupe.png"],
  coupe: ["/media/p-coupe.png", "/media/cat-coupe.png", "/media/fork-interior.png"],
  "sibir-sb3": ["/media/p-sibir.png", "/media/fork-entrance.png", "/media/cat-mirror.png"],
  "grand-ash": ["/media/p-grand.png", "/media/finish-oak.png", "/media/promo-2.png"],
  stroygost: ["/media/p-stroy.png", "/media/fork-entrance.png", "/media/hero-entrance.png"],
  "thermo-elite": ["/media/p-thermo.png", "/media/cat-thermo.png", "/media/hero-entrance.png"],
  "floor-nordic": ["/media/finish-white.png", "/media/finish-oak.png", "/media/hero-finish.png"],
  "floor-honey": ["/media/finish-oak.png", "/media/finish-cappuccino.png", "/media/g-extra-1.png"],
  "floor-walnut": ["/media/finish-graphite.png", "/media/finish-black.png", "/media/promo-1.png"],
  "floor-spc-stone": ["/media/finish-mint.png", "/media/finish-white.png", "/media/hero-showroom.png"],
  "floor-spc-oak": ["/media/finish-cappuccino.png", "/media/finish-oak.png", "/media/g-extra-2.png"],
  "floor-engineered": ["/media/g-extra-1.png", "/media/finish-oak.png", "/media/hero-finish.png"],
  "bamboo-natural": ["/media/finish-oak.png", "/media/cat-partition.png", "/media/g-extra-2.png"],
  "bamboo-carbon": ["/media/finish-black.png", "/media/finish-graphite.png", "/media/hero-hidden.png"],
  "bamboo-bleached": ["/media/finish-white.png", "/media/finish-mint.png", "/media/hero-finish.png"],
  "bamboo-slat": ["/media/cat-partition.png", "/media/finish-oak.png", "/media/g-extra-1.png"],
  "bamboo-slat-dark": ["/media/finish-graphite.png", "/media/finish-black.png", "/media/cat-hidden.png"],
  "bamboo-tile": ["/media/g-extra-2.png", "/media/finish-cappuccino.png", "/media/finish-oak.png"],
};

export const homeMedia = {
  promoA: "/media/promo-1.png",
  promoB: "/media/promo-2.png",
  help: "/media/help-banner.png",
  measure: ["/media/measure-1.png", "/media/p-turin.png", "/media/fork-interior.png"],
};

export const home = {
  h1: "Двери для дома,\nкоторый уже почти готов",
  h1Support: "Каталог, бесплатный замер и монтаж под ключ в Тюмени.",
  categoryForkTitle: "Выберите направление",
  categoryFork: [
    {
      title: "Входные",
      text: "Квартира и дом — с терморазрывом и ясной сметой монтажа.",
      href: "/catalog/entrance",
      priceFrom: "от 11 500 ₽",
      image: "/media/fork-entrance.png",
    },
    {
      title: "Межкомнатные",
      text: "Распашные, купе, скрытые — под стиль и бюджет ремонта.",
      href: "/catalog/interior",
      priceFrom: "от 5 400 ₽",
      image: "/media/fork-interior.png",
    },
  ],
  benefitsTitle: "Как мы закрываем покупку",
  benefits: [
    {
      title: "Бесплатный замер",
      text: "Проём, открывание и комплект — без скрытых доплат в разговоре.",
    },
    {
      title: "Своя доставка",
      text: "Привозим полотна и фурнитуру аккуратно, в согласованный день.",
    },
    {
      title: "Три салона",
      text: "Смотрите цвет и ручки вживую при нормальном свете.",
    },
    {
      title: "Монтаж под ключ",
      text: "Установка и облагораживание проёма одной бригадой.",
    },
  ],
  hitsTitle: "Сейчас берут чаще всего",
  hitsSupport: "Цена полотна на витрине — полный комплект внутри карточки.",
  promosTitle: "Условия, которые двигают сделку",
  howTitle: "Четыре шага без хаоса",
  howSteps: [
    { n: "01", title: "Замер", text: "Окно визита и перезвон за 10 минут." },
    { n: "02", title: "Подбор", text: "В салоне или онлайн — под стиль и бюджет." },
    { n: "03", title: "Договор", text: "Комплект, монтаж и сроки до оплаты." },
    { n: "04", title: "Установка", text: "Доставка, монтаж, приёмка работ." },
  ],
  helpTitle: "Нужен короткий путь к модели",
  helpText: "4 вопроса — подборка и купон 3 000 ₽ на комплект.",
  helpCta: "Подобрать за 2 минуты",
  reviewsTitle: "После монтажа",
  reviewsSupport: "Черновик отзывов — заменим на свежие с карт.",
  galleryTitle: "Как выглядит результат",
  gallerySupport: "Интерьеры вместо студийных вырезок.",
  measureBannerTitle: "Замерщик на объект",
  measureBannerText: "Ориентир по смете уже на визите.",
  stats: [
    { value: "12 000+", label: "установок в год" },
    { value: "11 лет", label: "на рынке" },
    { value: "3 салона", label: "с образцами" },
    { value: "96%", label: "рекомендуют" },
  ],
};

export const promos = [
  {
    id: "third",
    title: "Третье полотно в подарок",
    text: "На коллекции Optima Porte и LA STELLA — до конца месяца. Условия уточняйте у менеджера.",
    badge: "Хит акции",
  },
  {
    id: "install",
    title: "Установка каждой третьей двери — 0 ₽",
    text: "При заказе комплекта межкомнатных дверей с монтажом нашей бригадой.",
    badge: "Монтаж",
  },
  {
    id: "delivery",
    title: "Доставка по городу в подарок",
    text: "При покупке от 50 000 ₽. За город — по тарифу логистики.",
    badge: "Доставка",
  },
  {
    id: "credit",
    title: "Рассрочка 0–0–6",
    text: "Без первоначального взноса и переплаты на 6 месяцев — по одобрению банка.",
    badge: "Оплата",
  },
  {
    id: "pension",
    title: "Скидки новоселам и пенсионерам до 15%",
    text: "При предъявлении документов. Не суммируется с отдельными спецпредложениями.",
    badge: "Скидка",
  },
  {
    id: "hidden",
    title: "Скрытая дверь — спеццена",
    text: "Полный комплект скрытой системы от 25 000 ₽. Замер и консультация бесплатно.",
    badge: "Новинка",
  },
];

export const reviews = [
  {
    name: "Елена Тиунова",
    text: "Менеджер показала варианты от эконома до премиума. Входную поставили на следующий день, пять межкомнатных — за один день к нужной дате. Квартира сразу «собралась».",
    rating: 5,
  },
  {
    name: "Сергей Перескоков",
    text: "Грамотно объяснили комплектацию. Двери без косяков, монтажники быстро и аккуратно. Буду рекомендовать.",
    rating: 5,
  },
  {
    name: "Валерия Меркель",
    text: "Привезли быстро, поставили за четыре часа. Консультанты чёткие — без воды. Осталась довольна.",
    rating: 5,
  },
  {
    name: "Олег Харин",
    text: "В новостройке стояла «фольга». Подобрали входную под бюджет и объяснили, от чего зависит безопасность. Монтаж с позитивом.",
    rating: 5,
  },
];

export type ProductCategory =
  | "interior"
  | "entrance"
  | "hardware"
  | "flooring"
  | "bamboo";

export const catalogCategories: ProductCategory[] = [
  "interior",
  "entrance",
  "hardware",
  "flooring",
  "bamboo",
];

export const categoryMeta: Record<
  ProductCategory,
  {
    title: string;
    lead: string;
    kitLabels: [string, string, string, string];
    facets: {
      key: string;
      label: string;
      options: { value: string; label: string }[];
    }[];
  }
> = {
  interior: {
    title: "Межкомнатные двери",
    lead: "Распашные, купе, скрытые и перегородки — с прозрачной ценой комплекта.",
    kitLabels: ["Полотно", "Коробка", "Наличники", "Базовая фурнитура"],
    facets: [
      {
        key: "type",
        label: "Конструкция",
        options: [
          { value: "all", label: "Все" },
          { value: "swing", label: "Распашные" },
          { value: "sliding", label: "Купе" },
          { value: "folding", label: "Складные" },
          { value: "hidden", label: "Скрытые" },
          { value: "partition", label: "Перегородки" },
        ],
      },
      {
        key: "style",
        label: "Стиль",
        options: [
          { value: "all", label: "Все" },
          { value: "modern", label: "Современный" },
          { value: "neoclassic", label: "Неоклассика" },
          { value: "classic", label: "Классика" },
          { value: "loft", label: "Лофт" },
        ],
      },
      {
        key: "finish",
        label: "Отделка",
        options: [
          { value: "all", label: "Все" },
          { value: "eco", label: "Экошпон" },
          { value: "enamel", label: "Эмаль" },
          { value: "paint", label: "Под покраску" },
          { value: "glass", label: "Стекло / алюминий" },
        ],
      },
    ],
  },
  entrance: {
    title: "Входные двери",
    lead: "Квартира и дом — с терморазрывом, зеркалом и понятной сметой монтажа.",
    kitLabels: ["Полотно", "Коробка", "Наличники", "Базовая фурнитура"],
    facets: [
      {
        key: "purpose",
        label: "Назначение",
        options: [
          { value: "all", label: "Все" },
          { value: "flat", label: "Квартира" },
          { value: "house", label: "Дом" },
          { value: "economy", label: "Эконом / стройка" },
        ],
      },
      {
        key: "feature",
        label: "Конструкция",
        options: [
          { value: "all", label: "Все" },
          { value: "thermo", label: "Терморазрыв" },
          { value: "mirror", label: "Зеркало" },
          { value: "noise", label: "Шумоизоляция" },
          { value: "double", label: "Двустворчатые" },
        ],
      },
    ],
  },
  hardware: {
    title: "Фурнитура",
    lead: "Ручки, замки и комплектующие под выбранное полотно.",
    kitLabels: ["Изделие", "—", "—", "—"],
    facets: [
      {
        key: "cat",
        label: "Категория",
        options: [
          { value: "all", label: "Все" },
          { value: "handles", label: "Ручки" },
          { value: "locks", label: "Замки" },
        ],
      },
    ],
  },
  flooring: {
    title: "Напольные покрытия",
    lead: "Ламинат, SPC и инженерная доска — в тон дверям и панелям салона.",
    kitLabels: ["Покрытие", "Подложка", "Плинтус", "Пороги / стыки"],
    facets: [
      {
        key: "type",
        label: "Тип",
        options: [
          { value: "all", label: "Все" },
          { value: "laminate", label: "Ламинат" },
          { value: "engineered", label: "Инженерная" },
          { value: "spc", label: "SPC" },
          { value: "parquet", label: "Паркетная доска" },
        ],
      },
      {
        key: "tone",
        label: "Оттенок",
        options: [
          { value: "all", label: "Все" },
          { value: "light", label: "Светлый" },
          { value: "natural", label: "Натуральный" },
          { value: "dark", label: "Тёмный" },
        ],
      },
      {
        key: "grade",
        label: "Класс",
        options: [
          { value: "all", label: "Все" },
          { value: "33", label: "33 класс" },
          { value: "34", label: "34 класс" },
          { value: "wet", label: "Влагостойкий" },
        ],
      },
    ],
  },
  bamboo: {
    title: "Бамбуковые панели",
    lead: "Стеновые панели и рейки — тёплый акцент без тяжёлого монтажа.",
    kitLabels: ["Панели", "Профиль / старты", "Клей / крепёж", "Углы / торцы"],
    facets: [
      {
        key: "type",
        label: "Формат",
        options: [
          { value: "all", label: "Все" },
          { value: "wall", label: "Стеновые" },
          { value: "slat", label: "Рейки" },
          { value: "tile", label: "Декор-плитка" },
        ],
      },
      {
        key: "tone",
        label: "Цвет",
        options: [
          { value: "all", label: "Все" },
          { value: "natural", label: "Натуральный" },
          { value: "carbon", label: "Карбон" },
          { value: "bleached", label: "Выбеленный" },
        ],
      },
      {
        key: "mount",
        label: "Монтаж",
        options: [
          { value: "all", label: "Все" },
          { value: "glue", label: "Клей" },
          { value: "click", label: "Шип-паз" },
          { value: "batten", label: "Обрешётка" },
        ],
      },
    ],
  },
};

export type Product = {
  id: string;
  slug: string;
  category: ProductCategory;
  name: string;
  badge?: string;
  colorsExtra?: number;
  price: number;
  oldPrice?: number;
  finish: string;
  style: string;
  short: string;
  /** Ключи фильтров каталога (значения из URL) */
  filters?: Record<string, string>;
  /** Явно отмеченные «похожие» — для админки позже */
  relatedIds?: string[];
  kit: {
    leaf: number;
    frame: number;
    casings: number;
    hardwareBase: number;
    installFrom?: number;
  };
};

export const products: Product[] = [
  {
    id: "turin-507",
    slug: "turin-507-12",
    category: "interior",
    name: "Турин 507.12",
    badge: "Хит",
    colorsExtra: 6,
    price: 5400,
    oldPrice: 7714,
    finish: "Экошпон",
    style: "Современный",
    short: "Лёгкая межкомнатная модель для массовых проёмов. Часто берут комплектом на квартиру.",
    filters: { type: "swing", style: "modern", finish: "eco" },
    relatedIds: ["symphony", "coupe"],
    kit: { leaf: 5400, frame: 2100, casings: 1800, hardwareBase: 1200, installFrom: 2500 },
  },
  {
    id: "symphony",
    slug: "simfoniya-pg",
    category: "interior",
    name: "Симфония ПГ",
    badge: "−30%",
    price: 5885,
    oldPrice: 8407,
    finish: "Экошпон",
    style: "Неоклассика",
    short: "Глухое полотно с мягкой геометрией — спокойный фон для гостиной и спальни.",
    filters: { type: "swing", style: "neoclassic", finish: "eco" },
    relatedIds: ["turin-507", "rome"],
    kit: { leaf: 5885, frame: 2300, casings: 1900, hardwareBase: 1400, installFrom: 2500 },
  },
  {
    id: "hidden-line",
    slug: "skrytaya-linea",
    category: "interior",
    name: "Скрытая Linea Invisible",
    badge: "Новинка",
    price: 25000,
    finish: "Под покраску",
    style: "Минимализм",
    short: "Скрытый короб, полотно в плоскости стены. Полный комплект по спеццене.",
    filters: { type: "hidden", style: "modern", finish: "paint" },
    relatedIds: ["loft"],
    kit: { leaf: 16800, frame: 5200, casings: 0, hardwareBase: 3000, installFrom: 4500 },
  },
  {
    id: "rome",
    slug: "rim-pg",
    category: "interior",
    name: "Рим ПГ",
    colorsExtra: 1,
    price: 9268,
    oldPrice: 13240,
    finish: "Эмаль",
    style: "Классика",
    short: "Эмалевое покрытие для интерьеров, где важна «чистая» поверхность и цвет.",
    filters: { type: "swing", style: "classic", finish: "enamel" },
    relatedIds: ["symphony"],
    kit: { leaf: 9268, frame: 2800, casings: 2400, hardwareBase: 1800, installFrom: 2800 },
  },
  {
    id: "loft",
    slug: "loft-glass",
    category: "interior",
    name: "Лофт Glass",
    badge: "Новинка",
    colorsExtra: 4,
    price: 18900,
    finish: "Алюминий / стекло",
    style: "Лофт",
    short: "Стеклянная перегородка-дверь для зонирования без потери света.",
    filters: { type: "partition", style: "loft", finish: "glass" },
    relatedIds: ["hidden-line", "coupe"],
    kit: { leaf: 18900, frame: 4200, casings: 0, hardwareBase: 2600, installFrom: 4000 },
  },
  {
    id: "coupe",
    slug: "turin-coupe",
    category: "interior",
    name: "Турин 521.22 купе",
    colorsExtra: 5,
    price: 7425,
    oldPrice: 10607,
    finish: "Экошпон",
    style: "Купе",
    short: "Раздвижная система для узких коридоров и смежных комнат.",
    filters: { type: "sliding", style: "modern", finish: "eco" },
    relatedIds: ["turin-507", "loft"],
    kit: { leaf: 7425, frame: 0, casings: 0, hardwareBase: 5200, installFrom: 3500 },
  },
  {
    id: "porto-eco",
    slug: "porto-eco-8",
    category: "interior",
    name: "Порто Eco 8",
    badge: "Хит",
    colorsExtra: 8,
    price: 4990,
    oldPrice: 6200,
    finish: "Экошпон",
    style: "Современный",
    short: "Бюджетная распашная для типовых проёмов — часто берут комплектом на всю квартиру.",
    filters: { type: "swing", style: "modern", finish: "eco" },
    relatedIds: ["turin-507", "symphony"],
    kit: { leaf: 4990, frame: 1900, casings: 1600, hardwareBase: 1100, installFrom: 2400 },
  },
  {
    id: "velvet-enamel",
    slug: "velvet-enamel",
    category: "interior",
    name: "Velvet Эмаль",
    colorsExtra: 12,
    price: 11200,
    finish: "Эмаль",
    style: "Неоклассика",
    short: "Глухая эмаль с мягким блеском — гостиная и мастер-спальня.",
    filters: { type: "swing", style: "neoclassic", finish: "enamel" },
    relatedIds: ["rome", "symphony"],
    kit: { leaf: 11200, frame: 3000, casings: 2500, hardwareBase: 1900, installFrom: 2800 },
  },
  {
    id: "fold-smart",
    slug: "fold-smart-2",
    category: "interior",
    name: "Fold Smart 2",
    badge: "Новинка",
    price: 9800,
    finish: "Экошпон",
    style: "Складные",
    short: "Двустворчатая складная система для кладовых и узких ниш.",
    filters: { type: "folding", style: "modern", finish: "eco" },
    relatedIds: ["coupe", "porto-eco"],
    kit: { leaf: 9800, frame: 0, casings: 0, hardwareBase: 4100, installFrom: 3200 },
  },
  {
    id: "classic-pg",
    slug: "classic-pg-white",
    category: "interior",
    name: "Classic PG White",
    price: 13400,
    oldPrice: 15800,
    finish: "Эмаль",
    style: "Классика",
    short: "Белая классика с филёнкой — под лепнину и спокойные интерьеры.",
    filters: { type: "swing", style: "classic", finish: "enamel" },
    relatedIds: ["rome", "velvet-enamel"],
    kit: { leaf: 13400, frame: 3200, casings: 2600, hardwareBase: 2000, installFrom: 2900 },
  },
  {
    id: "invisible-pro",
    slug: "invisible-pro",
    category: "interior",
    name: "Invisible Pro",
    badge: "Новинка",
    price: 28900,
    finish: "Под покраску",
    style: "Минимализм",
    short: "Скрытый короб премиум-серии с усиленным полотном под покраску.",
    filters: { type: "hidden", style: "modern", finish: "paint" },
    relatedIds: ["hidden-line", "loft"],
    kit: { leaf: 19800, frame: 6100, casings: 0, hardwareBase: 3000, installFrom: 4800 },
  },
  {
    id: "glass-slim",
    slug: "glass-slim-partition",
    category: "interior",
    name: "Glass Slim Partition",
    colorsExtra: 3,
    price: 21500,
    finish: "Алюминий / стекло",
    style: "Лофт",
    short: "Тонкий алюминиевый профиль для зонирования кухни-гостиной.",
    filters: { type: "partition", style: "loft", finish: "glass" },
    relatedIds: ["loft", "coupe"],
    kit: { leaf: 21500, frame: 4800, casings: 0, hardwareBase: 2800, installFrom: 4200 },
  },
  {
    id: "sibir-sb3",
    slug: "sibir-sb-3",
    category: "entrance",
    name: "Сибирь СБ-3",
    badge: "Хит",
    price: 27500,
    finish: "МДФ / металл",
    style: "Квартира",
    short: "Надёжная входная для квартиры: понятная комплектация и быстрый монтаж.",
    filters: { purpose: "flat", feature: "noise" },
    relatedIds: ["grand-ash"],
    kit: { leaf: 27500, frame: 0, casings: 3500, hardwareBase: 0, installFrom: 4500 },
  },
  {
    id: "grand-ash",
    slug: "grand-yasen",
    category: "entrance",
    name: "Гранд ясень",
    badge: "Хит",
    price: 28990,
    finish: "МДФ ясень",
    style: "Квартира",
    short: "Тёплая фактура ясеня на панели — частый выбор для новостроек.",
    filters: { purpose: "flat", feature: "mirror" },
    relatedIds: ["sibir-sb3"],
    kit: { leaf: 28990, frame: 0, casings: 3800, hardwareBase: 0, installFrom: 4500 },
  },
  {
    id: "stroygost",
    slug: "stroygost-5",
    category: "entrance",
    name: "Стройгост 5 РФ",
    badge: "−15%",
    price: 11500,
    oldPrice: 13529,
    finish: "Металл",
    style: "Эконом",
    short: "Бюджетный входной контур для стройки и аренды без потери базовой безопасности.",
    filters: { purpose: "economy" },
    relatedIds: ["sibir-sb3"],
    kit: { leaf: 11500, frame: 0, casings: 2500, hardwareBase: 0, installFrom: 4000 },
  },
  {
    id: "thermo-elite",
    slug: "elit-termo",
    category: "entrance",
    name: "Элит Термо",
    price: 126690,
    oldPrice: 149047,
    finish: "Терморазрыв",
    style: "Дом",
    short: "Уличная дверь с терморазрывом для частного дома — когда важны тепло и тишина.",
    filters: { purpose: "house", feature: "thermo" },
    relatedIds: ["grand-ash"],
    kit: { leaf: 126690, frame: 0, casings: 0, hardwareBase: 0, installFrom: 8000 },
  },
  {
    id: "nord-flat",
    slug: "nord-flat-m",
    category: "entrance",
    name: "Nord Flat M",
    badge: "Хит",
    price: 24900,
    finish: "МДФ графит",
    style: "Квартира",
    short: "Лаконичная входная в графите — под современный холл новостройки.",
    filters: { purpose: "flat", feature: "noise" },
    relatedIds: ["sibir-sb3", "grand-ash"],
    kit: { leaf: 24900, frame: 0, casings: 3400, hardwareBase: 0, installFrom: 4500 },
  },
  {
    id: "mirror-line",
    slug: "mirror-line-90",
    category: "entrance",
    name: "Mirror Line 90",
    badge: "Новинка",
    price: 32900,
    finish: "МДФ / зеркало",
    style: "Квартира",
    short: "Входная с зеркальной панелью — визуально расширяет прихожую.",
    filters: { purpose: "flat", feature: "mirror" },
    relatedIds: ["grand-ash", "nord-flat"],
    kit: { leaf: 32900, frame: 0, casings: 3800, hardwareBase: 0, installFrom: 4800 },
  },
  {
    id: "cottage-termo",
    slug: "cottage-termo-x",
    category: "entrance",
    name: "Cottage Термо X",
    price: 89500,
    oldPrice: 98000,
    finish: "Терморазрыв",
    style: "Дом",
    short: "Уличная дверь с терморазрывом среднего сегмента для коттеджа.",
    filters: { purpose: "house", feature: "thermo" },
    relatedIds: ["thermo-elite"],
    kit: { leaf: 89500, frame: 0, casings: 0, hardwareBase: 0, installFrom: 7500 },
  },
  {
    id: "budget-steel",
    slug: "budget-steel-2",
    category: "entrance",
    name: "Budget Steel 2",
    price: 13900,
    finish: "Металл",
    style: "Эконом",
    short: "Простой стальной контур для стройки и временного входа.",
    filters: { purpose: "economy" },
    relatedIds: ["stroygost"],
    kit: { leaf: 13900, frame: 0, casings: 2600, hardwareBase: 0, installFrom: 4000 },
  },
  {
    id: "double-grand",
    slug: "double-grand",
    category: "entrance",
    name: "Double Grand",
    price: 62400,
    finish: "МДФ ясень",
    style: "Квартира",
    short: "Двустворчатая входная для широкого проёма в просторной прихожей.",
    filters: { purpose: "flat", feature: "double" },
    relatedIds: ["grand-ash", "mirror-line"],
    kit: { leaf: 62400, frame: 0, casings: 5200, hardwareBase: 0, installFrom: 6500 },
  },
  {
    id: "handle",
    slug: "ruchka-linea",
    category: "hardware",
    name: "Ручка Linea Soft",
    badge: "Фурнитура",
    price: 2890,
    finish: "Матовый хром",
    style: "Универсальная",
    short: "Тихая ручка с мягким ходом — ставят в комплекте с эмалью и экошпоном.",
    filters: { cat: "handles" },
    kit: { leaf: 2890, frame: 0, casings: 0, hardwareBase: 0 },
  },
  {
    id: "lock",
    slug: "zamok-secure",
    category: "hardware",
    name: "Замок Secure Pro",
    price: 4590,
    finish: "Сталь",
    style: "Входные",
    short: "Цилиндровый замок для входных дверей с защитой от высверливания.",
    filters: { cat: "locks" },
    kit: { leaf: 4590, frame: 0, casings: 0, hardwareBase: 0 },
  },
  // --- Напольные покрытия (6) ---
  {
    id: "floor-nordic",
    slug: "laminat-nordic-oak",
    category: "flooring",
    name: "Ламинат Nordic Oak 33",
    badge: "Хит",
    colorsExtra: 4,
    price: 1890,
    oldPrice: 2290,
    finish: "Дуб светлый",
    style: "Ламинат · м²",
    short: "Светлый дуб под скандинавский интерьер — стыкуется с белыми и эмалевыми дверями.",
    filters: { type: "laminate", tone: "light", grade: "33" },
    relatedIds: ["floor-honey", "bamboo-natural"],
    kit: { leaf: 1890, frame: 180, casings: 420, hardwareBase: 290, installFrom: 450 },
  },
  {
    id: "floor-honey",
    slug: "laminat-honey-oak",
    category: "flooring",
    name: "Ламинат Honey Oak 33",
    price: 2050,
    finish: "Дуб медовый",
    style: "Ламинат · м²",
    short: "Тёплый натуральный тон — частый выбор под экошпон и ясень на дверях.",
    filters: { type: "laminate", tone: "natural", grade: "33" },
    relatedIds: ["floor-nordic", "floor-walnut"],
    kit: { leaf: 2050, frame: 180, casings: 420, hardwareBase: 290, installFrom: 450 },
  },
  {
    id: "floor-walnut",
    slug: "laminat-graphite-walnut",
    category: "flooring",
    name: "Ламинат Graphite Walnut 34",
    badge: "Новинка",
    price: 2680,
    finish: "Орех графит",
    style: "Ламинат · м²",
    short: "Тёмный коммерческий класс — коридоры, кухни, активные зоны.",
    filters: { type: "laminate", tone: "dark", grade: "34" },
    relatedIds: ["floor-spc-stone", "bamboo-carbon"],
    kit: { leaf: 2680, frame: 220, casings: 480, hardwareBase: 320, installFrom: 500 },
  },
  {
    id: "floor-spc-stone",
    slug: "spc-stone-grey",
    category: "flooring",
    name: "SPC Stone Grey",
    badge: "Влагостойкий",
    price: 3120,
    oldPrice: 3490,
    finish: "Камень серый",
    style: "SPC · м²",
    short: "Жёсткая SPC-плита для влажных зон — без разбухания и с быстрым клик-замком.",
    filters: { type: "spc", tone: "light", grade: "wet" },
    relatedIds: ["floor-spc-oak", "floor-walnut"],
    kit: { leaf: 3120, frame: 0, casings: 520, hardwareBase: 360, installFrom: 550 },
  },
  {
    id: "floor-spc-oak",
    slug: "spc-oak-natural",
    category: "flooring",
    name: "SPC Oak Natural",
    price: 3350,
    finish: "Дуб натуральный",
    style: "SPC · м²",
    short: "Древесный рисунок на SPC — тёплый вид и влагостойкость одной позиции.",
    filters: { type: "spc", tone: "natural", grade: "wet" },
    relatedIds: ["floor-honey", "floor-engineered"],
    kit: { leaf: 3350, frame: 0, casings: 520, hardwareBase: 360, installFrom: 550 },
  },
  {
    id: "floor-engineered",
    slug: "inzhenernaya-yasen",
    category: "flooring",
    name: "Инженерная доска Ясень",
    badge: "Премиум",
    price: 5890,
    finish: "Ясень браш",
    style: "Инженерная · м²",
    short: "Живая фактура ясеня под паркетный вид — к дверям «Гранд ясень» и эмалям.",
    filters: { type: "engineered", tone: "natural", grade: "33" },
    relatedIds: ["floor-honey", "bamboo-natural"],
    kit: { leaf: 5890, frame: 320, casings: 680, hardwareBase: 410, installFrom: 900 },
  },
  // --- Бамбуковые панели (6) ---
  {
    id: "bamboo-natural",
    slug: "bambuk-wall-natural",
    category: "bamboo",
    name: "Бамбук Wall Natural",
    badge: "Хит",
    colorsExtra: 2,
    price: 4200,
    finish: "Натуральный",
    style: "Стеновые · м²",
    short: "Классическая стеновая панель — акцентная стена в гостиной или ТВ-зоне.",
    filters: { type: "wall", tone: "natural", mount: "glue" },
    relatedIds: ["bamboo-slat", "floor-honey"],
    kit: { leaf: 4200, frame: 680, casings: 520, hardwareBase: 390, installFrom: 700 },
  },
  {
    id: "bamboo-carbon",
    slug: "bambuk-wall-carbon",
    category: "bamboo",
    name: "Бамбук Wall Carbon",
    badge: "Новинка",
    price: 4580,
    oldPrice: 5100,
    finish: "Карбон",
    style: "Стеновые · м²",
    short: "Тёмный карбоновый тон — под графитовые двери и лофт-интерьеры.",
    filters: { type: "wall", tone: "carbon", mount: "glue" },
    relatedIds: ["bamboo-slat-dark", "floor-walnut"],
    kit: { leaf: 4580, frame: 680, casings: 520, hardwareBase: 390, installFrom: 700 },
  },
  {
    id: "bamboo-bleached",
    slug: "bambuk-wall-bleached",
    category: "bamboo",
    name: "Бамбук Wall Bleached",
    price: 4450,
    finish: "Выбеленный",
    style: "Стеновые · м²",
    short: "Светлый выбеленный бамбук — к эмалевым и скрытым дверям.",
    filters: { type: "wall", tone: "bleached", mount: "click" },
    relatedIds: ["bamboo-natural", "floor-nordic"],
    kit: { leaf: 4450, frame: 720, casings: 540, hardwareBase: 410, installFrom: 750 },
  },
  {
    id: "bamboo-slat",
    slug: "bambuk-reiki-natura",
    category: "bamboo",
    name: "Рейки Natura 40×20",
    badge: "Хит",
    price: 2890,
    finish: "Натуральный",
    style: "Рейки · м.п.",
    short: "Вертикальные ламели для зонирования и акустического фона.",
    filters: { type: "slat", tone: "natural", mount: "batten" },
    relatedIds: ["bamboo-natural", "bamboo-slat-dark"],
    kit: { leaf: 2890, frame: 450, casings: 280, hardwareBase: 220, installFrom: 500 },
  },
  {
    id: "bamboo-slat-dark",
    slug: "bambuk-reiki-carbon",
    category: "bamboo",
    name: "Рейки Carbon 40×20",
    price: 3050,
    finish: "Карбон",
    style: "Рейки · м.п.",
    short: "Тёмные рейки в системе на обрешётке — быстрый монтаж без мокрых работ.",
    filters: { type: "slat", tone: "carbon", mount: "batten" },
    relatedIds: ["bamboo-carbon", "bamboo-slat"],
    kit: { leaf: 3050, frame: 450, casings: 280, hardwareBase: 220, installFrom: 500 },
  },
  {
    id: "bamboo-tile",
    slug: "bambuk-plitka-mosaic",
    category: "bamboo",
    name: "Бамбук Mosaic Tile",
    badge: "Декор",
    price: 1980,
    finish: "Натуральный микс",
    style: "Плитка · м²",
    short: "Декоративная бамбуковая плитка для ниш, изголовья и небольших зон.",
    filters: { type: "tile", tone: "natural", mount: "glue" },
    relatedIds: ["bamboo-natural", "bamboo-bleached"],
    kit: { leaf: 1980, frame: 0, casings: 360, hardwareBase: 180, installFrom: 600 },
  },
  {
    id: "floor-oak-white",
    slug: "laminat-oak-white-33",
    category: "flooring",
    name: "Ламинат Oak White 33",
    price: 2190,
    finish: "Дуб белёный",
    style: "Ламинат · м²",
    short: "Светлый белёный дуб под скандинавские и эмалевые двери.",
    filters: { type: "laminate", tone: "light", grade: "33" },
    relatedIds: ["floor-nordic", "bamboo-bleached"],
    kit: { leaf: 2190, frame: 180, casings: 420, hardwareBase: 290, installFrom: 450 },
  },
  {
    id: "floor-wenge",
    slug: "laminat-wenge-34",
    category: "flooring",
    name: "Ламинат Wenge 34",
    badge: "Хит",
    price: 2790,
    finish: "Венге",
    style: "Ламинат · м²",
    short: "Глубокий тёмный тон для контраста со светлыми стенами.",
    filters: { type: "laminate", tone: "dark", grade: "34" },
    relatedIds: ["floor-walnut", "bamboo-carbon"],
    kit: { leaf: 2790, frame: 220, casings: 480, hardwareBase: 320, installFrom: 500 },
  },
  {
    id: "floor-spc-beige",
    slug: "spc-beige-soft",
    category: "flooring",
    name: "SPC Beige Soft",
    price: 2980,
    finish: "Бежевый камень",
    style: "SPC · м²",
    short: "Тёплый бежевый SPC для кухни и санузла.",
    filters: { type: "spc", tone: "light", grade: "wet" },
    relatedIds: ["floor-spc-stone", "floor-nordic"],
    kit: { leaf: 2980, frame: 0, casings: 520, hardwareBase: 360, installFrom: 550 },
  },
  {
    id: "floor-parquet-oak",
    slug: "parquet-oak-select",
    category: "flooring",
    name: "Паркетная доска Oak Select",
    badge: "Премиум",
    price: 6450,
    finish: "Дуб селект",
    style: "Паркетная · м²",
    short: "Селект-сорт дуба — спокойный рисунок под классику и неоклассику.",
    filters: { type: "parquet", tone: "natural", grade: "33" },
    relatedIds: ["floor-engineered", "floor-honey"],
    kit: { leaf: 6450, frame: 340, casings: 720, hardwareBase: 430, installFrom: 950 },
  },
  {
    id: "floor-spc-dark",
    slug: "spc-dark-slate",
    category: "flooring",
    name: "SPC Dark Slate",
    price: 3420,
    finish: "Тёмный сланец",
    style: "SPC · м²",
    short: "Каменный рисунок в тёмном тоне — лофт и графитовые двери.",
    filters: { type: "spc", tone: "dark", grade: "wet" },
    relatedIds: ["floor-walnut", "floor-spc-stone"],
    kit: { leaf: 3420, frame: 0, casings: 520, hardwareBase: 360, installFrom: 550 },
  },
  {
    id: "floor-ash-wide",
    slug: "inzhenernaya-ash-wide",
    category: "flooring",
    name: "Инженерная Ash Wide",
    price: 6120,
    finish: "Ясень широкий",
    style: "Инженерная · м²",
    short: "Широкая планка ясеня — меньше швов, больше «паркетного» вида.",
    filters: { type: "engineered", tone: "natural", grade: "33" },
    relatedIds: ["floor-engineered", "grand-ash"],
    kit: { leaf: 6120, frame: 320, casings: 680, hardwareBase: 410, installFrom: 900 },
  },
  {
    id: "bamboo-wide",
    slug: "bambuk-wall-wide",
    category: "bamboo",
    name: "Бамбук Wall Wide",
    price: 4680,
    finish: "Натуральный",
    style: "Стеновые · м²",
    short: "Широкая стеновая панель — быстрее закрывает площадь акцента.",
    filters: { type: "wall", tone: "natural", mount: "click" },
    relatedIds: ["bamboo-natural", "bamboo-slat"],
    kit: { leaf: 4680, frame: 720, casings: 540, hardwareBase: 410, installFrom: 750 },
  },
  {
    id: "bamboo-smoke",
    slug: "bambuk-wall-smoke",
    category: "bamboo",
    name: "Бамбук Wall Smoke",
    badge: "Новинка",
    price: 4720,
    finish: "Дымчатый",
    style: "Стеновые · м²",
    short: "Промежуточный тон между натуральным и карбоном.",
    filters: { type: "wall", tone: "carbon", mount: "glue" },
    relatedIds: ["bamboo-carbon", "bamboo-natural"],
    kit: { leaf: 4720, frame: 680, casings: 520, hardwareBase: 390, installFrom: 700 },
  },
  {
    id: "bamboo-slat-thin",
    slug: "bambuk-reiki-thin",
    category: "bamboo",
    name: "Рейки Thin 30×15",
    price: 2450,
    finish: "Натуральный",
    style: "Рейки · м.п.",
    short: "Тонкие ламели для лёгкого ритма на стене.",
    filters: { type: "slat", tone: "natural", mount: "batten" },
    relatedIds: ["bamboo-slat", "bamboo-natural"],
    kit: { leaf: 2450, frame: 420, casings: 260, hardwareBase: 200, installFrom: 480 },
  },
  {
    id: "bamboo-slat-bleach",
    slug: "bambuk-reiki-bleach",
    category: "bamboo",
    name: "Рейки Bleach 40×20",
    price: 2990,
    finish: "Выбеленный",
    style: "Рейки · м.п.",
    short: "Светлые рейки под эмаль и скрытые двери.",
    filters: { type: "slat", tone: "bleached", mount: "batten" },
    relatedIds: ["bamboo-bleached", "bamboo-slat"],
    kit: { leaf: 2990, frame: 450, casings: 280, hardwareBase: 220, installFrom: 500 },
  },
  {
    id: "bamboo-tile-dark",
    slug: "bambuk-plitka-dark",
    category: "bamboo",
    name: "Бамбук Mosaic Dark",
    price: 2150,
    finish: "Карбон микс",
    style: "Плитка · м²",
    short: "Тёмная декоративная плитка для ниш и изголовья.",
    filters: { type: "tile", tone: "carbon", mount: "glue" },
    relatedIds: ["bamboo-tile", "bamboo-carbon"],
    kit: { leaf: 2150, frame: 0, casings: 360, hardwareBase: 180, installFrom: 600 },
  },
  {
    id: "bamboo-acoustic",
    slug: "bambuk-acoustic-panel",
    category: "bamboo",
    name: "Acoustic Bamboo Panel",
    badge: "Хит",
    price: 5200,
    finish: "Натуральный",
    style: "Стеновые · м²",
    short: "Панель с мягким акустическим эффектом для ТВ-зоны и кабинета.",
    filters: { type: "wall", tone: "natural", mount: "batten" },
    relatedIds: ["bamboo-wide", "bamboo-slat"],
    kit: { leaf: 5200, frame: 780, casings: 560, hardwareBase: 420, installFrom: 800 },
  },
];
export const quiz = {
  title: "Подберём двери за 4 шага",
  subtitle: "В конце — подборка моделей и купон 3 000 ₽ на комплект.",
  couponLeft: 22,
  steps: [
    {
      id: "type",
      question: "Что выбираете?",
      options: ["Межкомнатные", "Входные", "И то и другое"],
    },
    {
      id: "style",
      question: "Какой характер интерьера?",
      options: ["Современный / минимализм", "Классика / неоклассика", "Лофт", "Пока не решили"],
    },
    {
      id: "budget",
      question: "Бюджет на одну дверь (комплект)?",
      options: ["до 15 000 ₽", "15–30 000 ₽", "30–60 000 ₽", "от 60 000 ₽"],
    },
    {
      id: "measure",
      question: "Размеры проёмов уже известны?",
      options: ["Да, есть замеры", "Нужен замерщик", "Только присматриваюсь"],
    },
  ],
  successTitle: "Подборка почти готова",
  successText:
    "Оставьте телефон — менеджер пришлёт 3–6 моделей под ваши ответы и активирует купон.",
};

export const measurePage = {
  title: "Бесплатный замер дверей",
  lead: "Инженер замерит проёмы, подскажет по открыванию и соберёт смету комплекта с монтажом.",
  sla: "Перезвоним в течение 10 минут в рабочее время салона.",
  fieldsNote: "Поля можно уточнить под CRM заказчика — сейчас черновик для демо.",
};

export const aboutPage = {
  title: "О магазине ШИКАРДОРС.РФ",
  lead: "Мы продаём не «полотно с витрины», а готовое решение: дверь + комплектация + монтаж с ответственностью.",
  mission:
    "Помогаем сделать дом тише, аккуратнее и законченнее — без сюрпризов в смете и срывов сроков установки.",
  points: [
    "Собственные бригады монтажа и обучение стандартам компании",
    "Три точки с образцами цвета и фурнитуры",
    "Прозрачная цена комплекта до договора",
    "Сопровождение от замера до приёмки работ",
  ],
};

export const servicesPage = {
  title: "Услуги",
  lead: "Всё, что нужно после выбора модели — в одном контуре.",
  items: [
    {
      id: "measure",
      title: "Бесплатный замер",
      text: "Выезд, консультация по открыванию, предварительный расчёт монтажа и доборов.",
    },
    {
      id: "install",
      title: "Установка дверей",
      text: "Межкомнатные и входные, облагораживание проёма, расширение и сужение.",
    },
    {
      id: "delivery",
      title: "Доставка и оплата",
      text: "Доставка по городу и за город, оплата картой, наличными, рассрочка 0–0–6.",
    },
    {
      id: "warranty",
      title: "Гарантия",
      text: "Гарантия производителя на изделия и гарантия на монтажные работы по договору.",
    },
  ],
};

export const contactsPage = {
  title: "Контакты",
  lead: "Приезжайте в удобный салон или вызовите замерщика на объект.",
};

export const footer = {
  about:
    "ШИКАРДОРС.РФ — салон дверей, полов и панелей в Тюмени. Каталог, замер, доставка и установка под ключ.",
  legal: "© ШИКАРДОРС.РФ. Демо-контент для согласования.",
  cols: [
    {
      title: "Покупателям",
      links: [
        { label: "Межкомнатные", href: "/catalog/interior" },
        { label: "Входные", href: "/catalog/entrance" },
        { label: "Напольные покрытия", href: "/catalog/flooring" },
        { label: "Бамбуковые панели", href: "/catalog/bamboo" },
        { label: "Замер", href: "/measure" },
      ],
    },
    {
      title: "Компания",
      links: [
        { label: "О магазине", href: "/about" },
        { label: "Контакты", href: "/contacts" },
        { label: "Для дизайнеров", href: "/about#designers" },
      ],
    },
  ],
};

export function formatPrice(n: number) {
  return new Intl.NumberFormat("ru-RU").format(n) + " ₽";
}

export function kitTotal(p: Product) {
  const k = p.kit;
  return k.leaf + k.frame + k.casings + k.hardwareBase;
}
